### ISSUE TITLE
After refactoring of the settings sidebar menu, I can't translate menu itens

### ISSUE THREAD

**Issue by p-moreira** [superdesk/superdesk-client-core#2623]

**Comment by petrjasek** [comment]
@tomaskikutis can you check pls?

**Comment by tomaskikutis** [comment]
I've created SDESK-3563 for this. It shouldn't be too hard for anyone to figure out. I'll take it if no one does until I finish with refactoring image upload.

**Comment by tomaskikutis** [comment]
I'm sorry about forgetting this issue for so long. I've just checked it and it works in the v1.27.1 release. It might also work in earlier ones, but I haven't checked that.
