### ISSUE TITLE
[Bug] Unable to publish due to all suggestions not being resolved

### ISSUE THREAD

**Issue by bfkolle** [superdesk/superdesk-client-core#2893]
In our production instance of Superdesk, we use the suggestion feature in articles for our review and copy-editing process. However, whenever we accept or reject all suggestions, it still refuses to let us publish saying that suggestions still need to be resolved (accepted/rejected). This happens over numerous articles and we've thoroughly checked all articles in question with multiple people to make sure no suggestions are left.

I am not 100% sure what commit we installed Superdesk on, but it was about a month ago.

**Comment by bfkolle** [comment]
![1](https://user-images.githubusercontent.com/9011528/54783592-24a0c780-4bf8-11e9-83ce-e10068334bf2.jpg)

**Comment by petrjasek** [comment]
hi, thx for info, we will check that

**Comment by karelpetrak** [comment]
Hi @bfkolle Can you check and paste here the Superdesk version you have? You can find it here:
![image](https://user-images.githubusercontent.com/14196385/54823711-f3340480-4ca8-11e9-845b-e0a8be008121.png)

**Comment by bfkolle** [comment]
Superdesk f11b991
Superdesk client rev. 1.27.1

Thanks!

**Comment by bfkolle** [comment]
Saw the commit that fixed this, thanks!
