### ISSUE TITLE
[Feature Request] Color-blind friendly suggestion colors in the editor

### ISSUE THREAD

**Issue by bfkolle** [superdesk/superdesk-client-core#2959]
Hello,

We use the suggestion feature in the editor for our copy-editing process, but the colors for the suggestion feature are green and red. Unfortunately, those are colors that color-blind people cannot see, and we have two of them on our staff.

In addition, it would also be nice to make suggestions more noticeable. Even when using a darker editor theme, it can be very difficult to see a small suggestion such as removing or adding a comma or period.

Thanks!

**Comment by fritzSF** [comment]
Hi @bfkolle ,
Thanks for the feedback. We will certainly look into it. Could you maybe give us more details on the type of colour-blindness your staff members have (e.g. Achromatopsia, Deuteranopia, Protanopia etc.)?

**Comment by bfkolle** [comment]
Thanks for looking into it. It is green/red color-blindness which I believe is Deuteranopia and/or Protanopia (they're pretty similar from what I have been looking at).

**Comment by fritzSF** [comment]
Thanks for the info, @bfkolle.

**Comment by petrjasek** [comment]
this should be resolved since 1.32
